//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelerSalakhutdinova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Аксессуары
    {
        public Аксессуары()
        {
            this.Выкройки = new HashSet<Выкройки>();
        }
    
        public int ID_аксессуара { get; set; }
        public string Наименование_аксессуара { get; set; }
        public string Тип { get; set; }
        public byte[] Фото { get; set; }
    
        public virtual ICollection<Выкройки> Выкройки { get; set; }
    }
}
