//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelerSalakhutdinova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Бухгалтерия
    {
        public int ID_зарплаты { get; set; }
        public Nullable<int> ID_сотрудника { get; set; }
        public Nullable<decimal> Зарплата { get; set; }
        public Nullable<decimal> Премия { get; set; }
        public Nullable<System.DateTime> Дата_зарплаты { get; set; }
    
        public virtual Сотрудник Сотрудник { get; set; }
    }
}
