//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelerSalakhutdinova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Выкройки
    {
        public Выкройки()
        {
            this.Заказ = new HashSet<Заказ>();
        }
    
        public int ID_выкройки { get; set; }
        public string Модель { get; set; }
        public byte[] Схема { get; set; }
        public byte[] Фото_модели { get; set; }
        public Nullable<int> ID_мерки { get; set; }
        public Nullable<int> ID_ткани { get; set; }
        public Nullable<int> ID_аксессуара { get; set; }
        public Nullable<int> Количество_ткани { get; set; }
    
        public virtual Аксессуары Аксессуары { get; set; }
        public virtual Мерки Мерки { get; set; }
        public virtual СкладТканей СкладТканей { get; set; }
        public virtual ICollection<Заказ> Заказ { get; set; }
    }
}
