//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelerSalakhutdinova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public int ID_заказа { get; set; }
        public Nullable<int> ID_заказчика { get; set; }
        public Nullable<int> ID_доставки { get; set; }
        public Nullable<int> ID_сотрудника { get; set; }
        public Nullable<int> ID_выкройки { get; set; }
        public Nullable<decimal> Цена_заказа { get; set; }
        public Nullable<decimal> Предоплата { get; set; }
        public string Дата_заказа { get; set; }
        public Nullable<bool> Срочность { get; set; }
    
        public virtual Выкройки Выкройки { get; set; }
        public virtual Доставка Доставка { get; set; }
        public virtual Клиент Клиент { get; set; }
        public virtual Состояние Состояние { get; set; }
    }
}
