//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelerSalakhutdinova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаписьНаМерку
    {
        public int ID_мерки { get; set; }
        public Nullable<int> ID_заказчика { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<System.TimeSpan> Время { get; set; }
    
        public virtual Клиент Клиент { get; set; }
    }
}
