//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelerSalakhutdinova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиент
    {
        public Клиент()
        {
            this.Заказ = new HashSet<Заказ>();
            this.ЗаписьНаМерку = new HashSet<ЗаписьНаМерку>();
        }
    
        public int ID_заказчика { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public Nullable<long> Контактный_телефон { get; set; }
        public string E_mail { get; set; }
        public string Password { get; set; }
        public Nullable<int> Количество_заказов { get; set; }
    
        public virtual ICollection<Заказ> Заказ { get; set; }
        public virtual ICollection<ЗаписьНаМерку> ЗаписьНаМерку { get; set; }
    }
}
