//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelerSalakhutdinova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Мерки
    {
        public Мерки()
        {
            this.Выкройки = new HashSet<Выкройки>();
        }
    
        public int ID_мерки { get; set; }
        public Nullable<int> Обхват_груди { get; set; }
        public Nullable<int> Обхват_талии { get; set; }
        public Nullable<int> Обхват_бедер { get; set; }
        public Nullable<int> Рост { get; set; }
        public string Примечания { get; set; }
    
        public virtual ICollection<Выкройки> Выкройки { get; set; }
    }
}
