//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelerSalakhutdinova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оборудование
    {
        public Оборудование()
        {
            this.СотрудникОборудование = new HashSet<СотрудникОборудование>();
        }
    
        public int ID_оборудования { get; set; }
        public string Наименование_оборудования { get; set; }
        public Nullable<System.DateTime> Дата_приобретения { get; set; }
        public Nullable<bool> Состояние { get; set; }
    
        public virtual ICollection<СотрудникОборудование> СотрудникОборудование { get; set; }
    }
}
