//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelerSalakhutdinova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class СведенияОТканях
    {
        public int ID_ткани { get; set; }
        public string Страна_производитель { get; set; }
        public Nullable<System.DateTime> Дата_изготовления { get; set; }
        public Nullable<System.DateTime> Дата_привоза { get; set; }
        public Nullable<decimal> Покупная_цена { get; set; }
    
        public virtual СкладТканей СкладТканей { get; set; }
    }
}
