//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelerSalakhutdinova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class СкладТканей
    {
        public СкладТканей()
        {
            this.Выкройки = new HashSet<Выкройки>();
        }
    
        public int ID_ткани { get; set; }
        public string Наименование_ткани { get; set; }
        public Nullable<int> Количество_ { get; set; }
        public string Состав_ткани { get; set; }
        public string Цвет { get; set; }
        public Nullable<decimal> Цена { get; set; }
    
        public virtual ICollection<Выкройки> Выкройки { get; set; }
        public virtual СведенияОТканях СведенияОТканях { get; set; }
    }
}
