//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelerSalakhutdinova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Состояние
    {
        public int ID_заказа { get; set; }
        public string Примечания { get; set; }
        public Nullable<bool> Состояние1 { get; set; }
    
        public virtual Заказ Заказ { get; set; }
    }
}
