//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelerSalakhutdinova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудник
    {
        public Сотрудник()
        {
            this.Бухгалтерия = new HashSet<Бухгалтерия>();
            this.Доставка = new HashSet<Доставка>();
            this.СотрудникОборудование = new HashSet<СотрудникОборудование>();
        }
    
        public int ID_сотрудника { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Должность { get; set; }
        public Nullable<System.DateTime> Дата_приема_на_работу { get; set; }
        public Nullable<int> Общий_стаж { get; set; }
        public Nullable<int> Стаж { get; set; }
        public Nullable<bool> Доступ_ко_всем_данным { get; set; }
        public string E_mail { get; set; }
        public string Password { get; set; }
        public Nullable<decimal> Оклад { get; set; }
    
        public virtual ICollection<Бухгалтерия> Бухгалтерия { get; set; }
        public virtual ICollection<Доставка> Доставка { get; set; }
        public virtual ICollection<СотрудникОборудование> СотрудникОборудование { get; set; }
    }
}
