//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelerSalakhutdinova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class СотрудникОборудование
    {
        public int ID_Связи { get; set; }
        public Nullable<int> ID_сотрудника { get; set; }
        public Nullable<int> ID_оборудования { get; set; }
    
        public virtual Оборудование Оборудование { get; set; }
        public virtual Сотрудник Сотрудник { get; set; }
    }
}
